version: "3.9"
services:
  backend:
    image: backend:1
    build:
      context: .
      dockerfile: ./devops/backend/Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - static_volume:/app/backend/static
      - media_volume:/app/backend/media
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: none
    depends_on:
      - db
    networks:
      - downtime

  db:
    image: postgres:16.2-alpine3.19
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - downtime

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./devops/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/backend/static
      - media_volume:/app/backend/media
    depends_on:
      - backend
    networks:
      - downtime

volumes:
  postgres_data:
  static_volume:
  media_volume:


networks:
  downtime:
